import { Button } from "@/components/ui/button";
import { listContent, type ContentKind, type ContentEntry } from "@shared/seo-content";
import { ArrowRight, BookOpen, Sparkles } from "lucide-react";
import { Link } from "wouter";

const config: Record<ContentKind, { label: string; title: string; description: string; base: string }> = {
  style: { label: "Styles", title: "Des rythmes à raconter.", description: "Des repères créatifs pour décrire des univers musicaux africains avec respect, précision et originalité.", base: "/styles" },
  mood: { label: "Ambiances", title: "Choisissez l’énergie avant le son.", description: "Explorez les intentions qui donnent une direction à votre prochain morceau AfroMuse.", base: "/ambiances" },
  guide: { label: "Guides", title: "Une idée claire devient une meilleure création.", description: "Des méthodes concrètes pour écrire un prompt musical original et utilisable.", base: "/guides" },
  useCase: { label: "Cas d’usage", title: "Des créations pensées pour de vrais projets.", description: "Des directions musicales responsables pour donner une signature à vos usages.", base: "/cas-usages" },
};

export function ContentHub({ kind }: { kind: ContentKind }) {
  const page = config[kind]; const entries = listContent(kind);
  return <main className="min-h-screen bg-[#09090b] text-zinc-100"><header className="container flex h-20 items-center justify-between"><Link href="/" className="font-semibold">AfroMuse <span className="text-amber-300">AI</span></Link><Link href="/connexion"><Button className="rounded-full bg-amber-300 text-zinc-950 hover:bg-amber-200">Créer une musique</Button></Link></header><section className="container py-16 sm:py-24"><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-300">{page.label}</p><h1 className="mt-4 max-w-3xl font-serif text-5xl tracking-[-.05em] text-white sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-zinc-400">{page.description}</p><div className="mt-14 grid gap-5 md:grid-cols-2">{entries.map(entry => <ContentCard key={entry.slug} entry={entry} path={`${page.base}/${entry.slug}`} />)}</div></section></main>;
}

function ContentCard({ entry, path }: { entry: ContentEntry; path: string }) { return <article className="rounded-3xl border border-white/10 bg-white/[.025] p-7 transition hover:border-amber-300/40"><BookOpen className="h-5 w-5 text-amber-300" /><h2 className="mt-8 font-serif text-3xl text-white">{entry.shortTitle}</h2><p className="mt-3 leading-relaxed text-zinc-400">{entry.description}</p><Link href={path} className="mt-7 inline-flex items-center text-sm font-semibold text-amber-200 hover:text-amber-300">Lire la fiche <ArrowRight className="ml-2 h-4 w-4" /></Link></article>; }

export function ContentDetail({ entry }: { entry: ContentEntry }) { return <main className="min-h-screen bg-[#09090b] text-zinc-100"><header className="container flex h-20 items-center justify-between"><Link href="/" className="font-semibold">AfroMuse <span className="text-amber-300">AI</span></Link><Link href="/connexion"><Button className="rounded-full bg-amber-300 text-zinc-950 hover:bg-amber-200">Essayer AfroMuse</Button></Link></header><article className="container max-w-3xl py-14 sm:py-24"><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-300">{config[entry.kind].label} · Mis à jour le {new Date(`${entry.updatedAt}T12:00:00Z`).toLocaleDateString("fr-FR")}</p><h1 className="mt-5 font-serif text-5xl tracking-[-.05em] text-white sm:text-6xl">{entry.title}</h1><p className="mt-8 text-xl leading-relaxed text-zinc-300">{entry.intro}</p><section className="mt-12 rounded-3xl border border-amber-300/20 bg-amber-300/[.07] p-7"><div className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.14em] text-amber-200"><Sparkles className="h-4 w-4" /> Exemple de direction originale</div><p className="mt-5 leading-relaxed text-zinc-100">{entry.prompt}</p></section><section className="mt-12"><h2 className="font-serif text-3xl text-white">Passer de l’idée au morceau</h2><p className="mt-4 leading-relaxed text-zinc-400">Dans le studio AfroMuse, choisissez le style, l’ambiance, la durée et le format, puis adaptez cette direction à votre propre contexte. Évitez les noms d’artistes, les paroles et les œuvres existantes.</p><Link href="/connexion"><Button className="mt-7 rounded-full bg-amber-300 text-zinc-950 hover:bg-amber-200">Ouvrir le studio <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></section><section className="mt-14 border-t border-white/10 pt-10"><h2 className="font-serif text-3xl text-white">À explorer aussi</h2><div className="mt-6 flex flex-wrap gap-3">{entry.related.map(related => <span key={related} className="rounded-full border border-white/10 px-4 py-2 text-sm text-zinc-300">{related}</span>)}</div></section></article></main>; }
