import { Link } from "wouter";

export default function Legal({ type }: { type: "cgu" | "confidentialite" }) {
  const privacy = type === "confidentialite";
  const title = privacy ? "Politique de confidentialité" : "Conditions d’utilisation";
  const sections = privacy ? [
    ["Données traitées", "AfroMuse traite les données nécessaires à la création et à la gestion d’un compte, à la bibliothèque audio, au portefeuille de crédits, aux paiements, au support et à la liaison facultative d’un numéro WhatsApp."],
    ["Finalités et prestataires", "Ces données servent au fonctionnement du service, à la sécurité, à la prévention de la fraude, à l’exécution des paiements et à l’envoi d’informations transactionnelles. Les prestataires effectivement activés pour la génération musicale, l’email, le paiement, le stockage et WhatsApp devront être listés dans la version de production."],
    ["Durée et sécurité", "Les durées de conservation doivent être définies selon la finalité, les obligations applicables et les délais de prescription. AfroMuse doit mettre en œuvre des mesures techniques et organisationnelles proportionnées pour protéger les données."],
    ["Vos droits", "Selon votre pays de résidence et le droit applicable, vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou l’opposition au traitement de vos données. Les coordonnées du contact vie privée doivent être renseignées avant la publication définitive."],
  ] : [
    ["Accès au service", "Vous êtes responsable de l’exactitude des informations fournies, de la confidentialité de votre accès et de l’usage de votre compte. Un seul numéro WhatsApp peut être associé à un compte à la fois, après vérification par email."],
    ["Crédits et paiements", "Les crédits sont réservés avant une génération et consommés lorsqu’elle aboutit. Une commande est liée au compte bénéficiaire : une autre personne peut régler son lien de paiement sans devenir bénéficiaire des crédits."],
    ["Créations et usages", "Vous êtes responsable des prompts, fichiers et usages de vos créations. Les conditions de droits, de disponibilité et d’usage commercial doivent être vérifiées auprès des fournisseurs de génération ainsi que dans le plan AfroMuse applicable."],
    ["Restrictions", "Il est interdit d’utiliser AfroMuse pour reproduire ou faire passer une création pour celle d’un tiers, contourner les règles du service, porter atteinte à des droits ou soumettre des contenus illicites. AfroMuse peut suspendre un accès en cas d’usage abusif."],
  ];
  return <main className="min-h-screen bg-[#09090b] text-zinc-200"><header className="container flex h-20 items-center"><Link href="/" className="font-semibold text-white">← AfroMuse <span className="text-amber-300">AI</span></Link></header><article className="container max-w-3xl py-12 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[.16em] text-amber-300">Informations de confiance</p><h1 className="mt-4 font-serif text-5xl tracking-[-.045em] text-white">{title}</h1><p className="mt-5 text-sm text-zinc-500">Dernière mise à jour : 15 août 2026. Brouillon à relire par un conseil qualifié avant publication commerciale définitive.</p><div className="mt-10 space-y-10 prose prose-invert max-w-none prose-p:text-zinc-400 prose-headings:font-serif">{sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</div><nav className="mt-14 flex flex-wrap gap-4 border-t border-white/10 pt-7 text-sm text-amber-200"><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-cookies">Cookies</Link><Link href="/politique-contenu-ia">Contenu IA</Link><Link href="/contact">Contact</Link></nav></article></main>;
}
