import { Link } from "wouter";

type TrustPage = "mentions" | "cookies" | "ai";
const content: Record<TrustPage, { eyebrow: string; title: string; updated: string; sections: Array<[string, string]> }> = {
  mentions: { eyebrow: "Informations de confiance", title: "Mentions légales", updated: "15 août 2026", sections: [["Éditeur", "AfroMuse AI est un service numérique de création musicale IA. Les informations d’identification de l’éditeur — raison sociale, forme juridique, numéro d’immatriculation, adresse, pays de constitution et directeur de publication — doivent être renseignées avant la publication commerciale définitive."], ["Contact", "Pour toute demande liée au service, utilisez la page de contact. L’adresse d’assistance et, le cas échéant, les coordonnées du responsable de la protection des données doivent être publiées ici avant le lancement."], ["Hébergement et prestataires", "L’infrastructure applicative, le stockage, l’email transactionnel, le paiement, la génération musicale et WhatsApp peuvent faire intervenir des prestataires techniques. Leur liste à jour est détaillée dans la politique de confidentialité une fois la configuration de production finalisée."], ["Propriété intellectuelle", "Les marques, interfaces, contenus éditoriaux et éléments de l’application sont protégés selon les droits applicables. Les utilisateurs restent responsables des contenus, prompts et usages qu’ils soumettent au service."]] },
  cookies: { eyebrow: "Confidentialité", title: "Politique cookies", updated: "15 août 2026", sections: [["Principe", "AfroMuse utilise les technologies strictement nécessaires au fonctionnement, à la sécurité des sessions et à la mémorisation des préférences techniques. Les outils de mesure ne doivent être activés qu’après information appropriée et, lorsque requis, recueil du consentement."], ["Catégories", "Les cookies nécessaires servent notamment à maintenir une session authentifiée et à protéger le service. Les cookies de mesure ou marketing, s’ils sont activés, seront listés avec leur finalité, leur fournisseur et leur durée de conservation."], ["Vos choix", "Vous pouvez paramétrer votre navigateur pour limiter ou supprimer les cookies. Le refus de certains cookies nécessaires peut toutefois empêcher l’accès à des fonctionnalités d’AfroMuse."], ["Mise à jour", "Cette page doit être revue à chaque ajout d’un outil de mesure, de publicité, de paiement ou de support tiers."]] },
  ai: { eyebrow: "Création responsable", title: "Politique de contenu IA", updated: "15 août 2026", sections: [["Créations originales", "AfroMuse est conçu pour aider à formuler des directions musicales originales. Décrivez une ambiance, un rythme, une instrumentation ou un contexte ; évitez de demander la copie, l’imitation ou la reconstitution d’un artiste, d’une œuvre, de paroles ou d’un enregistrement existant."], ["Contenus interdits", "Ne soumettez pas de contenu illicite, haineux, menaçant, trompeur, portant atteinte à la vie privée, ou dont vous ne détenez pas les droits nécessaires. Ne créez pas de contenu destiné à induire une affiliation ou une validation fausse."], ["Usage commercial", "Les conditions d’usage des fichiers générés dépendent notamment du fournisseur de génération, du plan souscrit et du droit applicable. Vérifiez les conditions en vigueur avant toute exploitation commerciale, diffusion ou monétisation."], ["Signalement", "Pour signaler une atteinte présumée, un abus ou une demande de retrait, contactez l’équipe AfroMuse en décrivant précisément le contenu concerné, l’URL ou l’identifiant, et le motif de votre demande."]] },
};

export default function Trust({ type }: { type: TrustPage }) { const page = content[type]; return <main className="min-h-screen bg-[#09090b] text-zinc-200"><header className="container flex h-20 items-center"><Link href="/" className="font-semibold text-white">← AfroMuse <span className="text-amber-300">AI</span></Link></header><article className="container max-w-3xl py-12 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[.16em] text-amber-300">{page.eyebrow}</p><h1 className="mt-4 font-serif text-5xl tracking-[-.045em] text-white">{page.title}</h1><p className="mt-5 text-sm text-zinc-500">Dernière mise à jour : {page.updated}. Document de travail à adapter à votre entité, à vos pays d’exploitation et à vos prestataires effectifs.</p><div className="mt-10 space-y-10 prose prose-invert max-w-none prose-p:text-zinc-400 prose-headings:font-serif">{page.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</div><nav className="mt-14 flex flex-wrap gap-4 border-t border-white/10 pt-7 text-sm text-amber-200"><Link href="/cgu">CGU</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/politique-cookies">Cookies</Link><Link href="/politique-contenu-ia">Contenu IA</Link><Link href="/contact">Contact</Link></nav></article></main>; }
